### ISSUE TITLE
Possibility of adjusting the time of actionbarmessage?

### ISSUE THREAD

**Issue by catches** [BlitzOffline/FrozenJoin#1]
Basically what the title says, I have this: `  - '[ACTIONBARMESSAGE] &aType /help to get started.'` and I would like to adjust the time it takes for the action bar message to go away.

**Comment by catches** [comment]
Also add an option to allow the join/leave message to be after the motd, since setting a delay makes the join/leave message blank if the user spam joins and leaves.

@BlitzOffline

**Comment by BlitzOffline** [comment]
I somehow completely missed this post until now. Sorry about that.

From what I gather, it is impossible to change the time an action bar stays for within spigot, paper or adventure. By default actions stay for 3 seconds. You could make it stay for longer if you keep sending action bars however. So I could probably make this happen but the minimum display time would be 3 seconds.

And about the second issue, any chance you can provide video of this happening? I am very intrigued. I can definitely just switch what is being sent first (format then motd). Also can you send your config with the video?

**Comment by catches** [comment]
Hmm I see, idk if I can send a video, but it's basically something like this, if the user spam joins and leaves the server.
![image](https://user-images.githubusercontent.com/105005455/217072892-302df18d-d66f-4bd2-8b32-17a885877422.png)
![image](https://user-images.githubusercontent.com/105005455/217072927-2c8388cb-4610-497a-a4ff-043f33c04c2f.png)
I assume the delay I added is what is causing the blank messages.

My config:
https://paste.helpch.at/ebuzacixiv.bash

**Comment by catches** [comment]
Hi @BlitzOffline :D

Did you receive my reply?

**Comment by BlitzOffline** [comment]
Yes I have. I just didn't have any time to look into it unfortunately.

**Comment by BlitzOffline** [comment]
So I've started investigating today and I could not replicate the issue.

This is my server setup: https://paste.helpch.at/ejayukukog
I've also used your FrozenJoin config and the user that was leaving and joining had the permissions frozenjoin.default and frozenjoin.motd

I have repeatedly rejoined the server about 20+ times.

![image](https://user-images.githubusercontent.com/52609756/233780574-30cccd58-b222-4f84-aec4-322978d8d5a2.png)

**Comment by BlitzOffline** [comment]
Update on the feature request however, I am getting somewhere. Here's a preview

https://user-images.githubusercontent.com/52609756/233783668-a797a5c8-a410-4db0-9344-d87b47245a8a.mp4

**Comment by BlitzOffline** [comment]
I'm going to close this issue as I've added the feature request. If the other problem still persists for you please open a new issue.

Closed by 33162a2e66cac782e9204db71c22f00a332f277d

Added 2 new actions:
`- '[PERSISTENTACTIONBARMESSAGE]<time>;<message>'`
`- '[PERSISTENTACTIONBARBROADCAST]<time>;message'`
The time is in seconds.

Jar with the new actions:
[FrozenJoin-2.3.2-builds.zip](https://github.com/BlitzOffline/FrozenJoin/files/11301348/FrozenJoin-2.3.2-builds.zip)

CC: @catches
